WebMarket/WebMarket.Admin/Controllers/VariantController.cs
using System.Web.Mvc;
using Aware;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Model;
using Aware.Util;
using Aware.Util.Model;
using Aware.Util.Enums;

namespace WebMarket.Admin.Controllers
{
    public class VariantController : BaseController
    {
        private readonly IVariantService _variantService;
        public VariantController(IVariantService variantService)
        {
            _variantService = variantService;
        }

        public ActionResult Index()
        {
            IsSuper();
            var model = _variantService.GetVariantListModel();
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var isSuper = IsSuper(false);
            if (!isSuper && id == 0)
            {
                return RedirectToAction("Index");
            }

            var model = _variantService.GetVariantDetail(id);
            if (model != null)
            {
                model.AllowEdit = isSuper;
                model.SaveResult = (Result)TempData["SaveResult"];
            }
            return View(model);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public ActionResult Detail(VariantProperty model)
        {
            var result = Result.Error(Resource.General_Error);
            if (ModelState.IsValid)
            {
                var isNew = model != null && model.ID == 0;
                result = _variantService.SaveVariantProperty(model);
                if (result.OK && isNew)
                {
                    var id = (int)result.Value;
                    return RedirectToRoute(Helper.RouteNames.VariantDetailRoute, new { name = model.Name.ToSeoUrl(), id });
                }
            }

            TempData["SaveResult"] = result;
            return Detail(model.ID);
        }

        [HttpPost]
        public JsonResult GetVariantRelations(int relationID, int relationType)
        {
            var model = _variantService.GetVariantRelations(relationID, relationType);
            return Json(new { model }, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        public JsonResult DeleteVariantProperty(int id)
        {
            var result = _variantService.DeleteVariantProperty(id);
            return ResultValue(result);
        }

        [HttpPost]
        public JsonResult SaveVariantRelation(VariantRelation relation)
        {
            relation.Status = Statuses.Active;
            var result = _variantService.SaveVariantRelation(relation);
            return Json(new { success = result.IsSuccess, id = (int)result.Value });
        }

        [HttpPost]
        public JsonResult DeleteVariantRelation(int id)
        {
            var result = _variantService.DeleteVariantRelation(id);
            return Json(new { success = result.IsSuccess });
        }

        [HttpPost]
        public JsonResult SaveVariantSelection(VariantSelection selection)
        {
            var result = _variantService.SaveVariantSelection(selection);
            return Json(new { success = result.IsSuccess, id = (int)result.Value });
        }

        [HttpPost]
        public JsonResult DeleteVariantSelection(int selectionID)
        {
            var result = _variantService.DeleteVariantSelection(selectionID);
            return Json(new { success = result.IsSuccess });
        }
    }
}

WebMarket/WebMarket.Admin/Views/Variant/Detail.cshtml
@using Aware.ECommerce.Util
@using Aware.Util.Enums
@using Aware.Util.Model
@using Aware.Util.View
@using WebMarket.Admin.Helper

@model Aware.ECommerce.Model.VariantDetailModel
@{

    var property = Model != null ? Model.VariantProperty : null;
    ViewBag.SaveResult = Model != null ? Model.SaveResult : null;

    ViewBag.Title = "Varyant Detay";
    if (property != null)
    {
        ViewBag.Title = property != null && property.ID > 0 ? property.Name : "Yeni Varyant Özellik";
    }

    ViewBag.PageNavigation = new Item(0, "Varyant Özellikler", "fa-th", "/varyant-ozellikler");
    TempData["ActivePage"] = 11;
}

<section class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-th"></i></div>
                <div class="card-content">
                    <h2 class="card-title">@ViewBag.Title</h2>
                    @if (property == null)
                    {
                        <hr />
                        <div class="no-result-found">
                            <i class="fa fa-warning"></i>
                            <h4>Varyant Özellik Bulunamadı</h4>
                            <p class="description">Böyle bir özellik bulunamadı ya da görüntüleme yetkiniz yok!</p>
                        </div>
                    }
                    else
                    {
                        <div class="box box-info property-detail-panel">
                            <div class="box-header">

                            </div>
                            @using (Html.BeginForm("Detail", "Variant", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                            {
                                <div class="box-body">
                                    @if (Model.AllowEdit)
                                    {
                                        var fields = new FieldHelper(FieldDirection.Horizantal, 3);
                                        fields.Label("#ID", property.ID.ToString(), "viewable");
                                        fields.Text("Name", "İsim", property.Name, "validate", 100);
                                        fields.Text("DisplayName", "Görünen İsim", property.DisplayName, "validate", 100);
                                        fields.Select("Gösterim Şekli", "DisplayMode", Model.PropertyDisplayModes, (int)property.DisplayMode, "display-mode-selector", string.Empty);
                                        fields.Number("MaxSelection", "Max Seçim", property.MaxSelection.ToString(), "pnumber", 3);
                                        fields.Text("SortOrder", "Sıra", property.SortOrder, "", 3);
                                        fields.Select("Durum", "Status", Model.StatusList, (int)property.Status, "status-selector", string.Empty);
                                        fields.CheckBox("IsRequired", "Zorunlu Mu?", property.IsRequired);
                                        fields.CheckBox("TrackStock", "Stok Takibi?", property.TrackStock);

                                        @Html.Hidden("ID", property.ID)
                                        @Html.Partial("_FieldHelper", fields)

                                        <hr />
                                        <div class="text-right field-row button-row">
                                            @if (property.ID > 0)
                                            {
                                                var childCount = Model.ChildList != null ? Model.ChildList.Count() : 0;
                                                @Html.ButtonFor("Sil", "mr10 btn-danger btn-delete-variant", "remove", "data-id='" + property.ID + "' data-childs='" + childCount + "'")
                                            }
                                            @Html.ButtonFor("Kaydet", "btn-success btn-save-property")
                                        </div>
                                    }
                                    else
                                    {
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                                <tr>
                                                    <td class="text-bold" width="20%">ID</td>
                                                    <td>@property.ID</td>
                                                </tr>
                                                <tr>
                                                    <td class="text-bold">İsim</td>
                                                    <td>@property.Name</td>
                                                </tr>
                                                <tr>
                                                    <td class="text-bold">Gösterim Şekli</td>
                                                    <td>@Html.LookupValue(Model.PropertyDisplayModes, (int)property.DisplayMode)</td>
                                                </tr>
                                                <tr>
                                                    <td class="text-bold">Zorunlu Mu?</td>
                                                    <td class="text-center"><i class="fa @(property.IsRequired ? "text-green fa-check" : "text-red fa-remove")"></i></td>
                                                </tr>
                                                <tr>
                                                    <td class="text-bold">Stok Takibi?</td>
                                                    <td class="text-center"><i class="fa @(property.TrackStock ? "text-green fa-check" : "text-red fa-remove")"></i></td>
                                                </tr>
                                                <tr>
                                                    <td class="text-bold">Durum</td>
                                                    <td>@Html.StatusFor(property.Status)</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    }
                                </div>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>

        @if (property != null && property.ID > 0)
        {
            @Html.Partial("~/Views/Property/_SubPropertyView.cshtml", property.AsPropertyView(Model.ChildList, Model.AllowEdit))
        }
    </div>
</section>

@section pageheader{
    <script src="~/resource/js/property.js"></script>
}

WebMarket/WebMarket.Admin/Views/Variant/Index.cshtml
@using Aware.Util
@using WebMarket.Admin.Helper;
@model Aware.ECommerce.Model.VariantListModel
@{
    ViewBag.Title = "Varyant Özellikler";
    TempData["ActivePage"] = 11;
    var count = Model != null && Model.VariantProperties != null ? Model.VariantProperties.Count : 0;
}

<section class="content-header variant-properties">
    <div class="row">
        <div class="col-md-9 col-sm-12">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-th"></i></div>
                <div class="card-content">
                    <h2 class="card-title">
                        @ViewBag.Title
                        @if (ViewBag.IsSuper)
                        {
                            <a href="@Url.Action("Detail", new { name = "yeni-özellik", id = 0 })" class="btn btn-info btn-round btn-fab btn-fab-mini ml20" title="Yeni Ekle"><i class="fa fa-plus"></i></a>
                        }
                    </h2>

                    @if (count>0)
                    {
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="5%">#ID</th>
                                        <th width="22%">Özellik</th>
                                        <th width="12%">Zorunlu Mu?</th>
                                        <th width="12%">Stok Takibi?</th>
                                        <th width="15%">Gösterim Şekli</th>
                                        <th width="5%">Sıra</th>
                                        <th width="10%">Durumu</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var property in Model.VariantProperties)
                                    {
                                        <tr>
                                            <td>@property.ID</td>
                                            <td class="td-name">@property.Name</td>
                                            <td class="text-center"><i class="fa @(property.IsRequired ? "text-green fa-check" : "text-red fa-remove")"></i></td>
                                            <td class="text-center"><i class="fa @(property.TrackStock ? "text-green fa-check" : "text-red fa-remove")"></i></td>
                                            <td>@Html.LookupValue(Model.PropertyDisplayModes, (int)property.DisplayMode)</td>
                                            <td class="text-center">@property.SortOrder</td>
                                            <td class="text-center">
                                                @Html.StatusFor(property.Status)
                                            </td>
                                            <td>
                                                <a href="@Url.Action("Detail", new {name = property.Name.ToSeoUrl(), id = property.ID})" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Güncelle</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    }
                    else
                    {
                        <hr />
                        <div class="no-result-found">
                            <i class="fa fa-warning"></i>
                            <h4>Listelenecek Özellik Bulunamadı</h4>
                            @if (ViewBag.IsSuper)
                            {
                                <p class="description"><b>Yeni Ekle</b> butonunu kullanarak yeni bir varyant tanımıyapabilirsiniz.</p>
                            }
                            else
                            {
                                <p class="description">Tanımlı varyant özellik olduğunda bu alanda listelenecektir.</p>
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section pageheader{
    <style>
        .variant-properties td i.fa { font-size: 20px;}
    </style>
}

WebMarket/WebMarket.Admin/Views/Variant/_VariantRelations.cshtml
@using WebMarket.Admin.Helper
@model Aware.ECommerce.Model.VariantRelationViewModel

<div class="variant-relations">
    <input type="hidden" id="RelationID" ng-init="relationID=@Model.RelationID" ng-value="{{relationID}}" />
    <input type="hidden" id="RelationType" ng-init="relationType=@((int)Model.RelationType)" ng-value="{{relationType}}" />

    <p ng-show="variantRelations.length==0" class="text-red text-bold mb20">
        Henüz eklediğiniz bir varyant özellik yok!
    </p>

    <table class="table">
        <thead>
            <tr>
                <th width="5%">#ID</th>
                <th width="15%">Özellik</th>
                <th width="15%">Değer</th>
                <th width="15%">Fiyat (<i class="fa fa-turkish-lira"></i>)</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="relation in variantRelations | orderBy:'VariantID'">
                <td>{{relation.ID}}</td>
                <td>{{getName(relation,'P')}}</td>
                <td>{{getName(relation,'O')}}</td>
                <td>
                    <input type="text" class="form-control text-right" name="Price" ng-model="relation.Price" maxlength="6" />
                </td>
                <td>
                    @Html.ButtonFor("Güncelle", "btn-sm btn-success", "check", "ng-click='saveRelation(relation)'")
                    @Html.ButtonFor("Sil", "btn-sm btn-danger", "remove", "ng-click='removeRelation(relation)'")
                </td>
            </tr>

            <tr>
                <td>{{newRelation.ID}}</td>
                <td>
                    <select ng-model="newRelation.VariantID" class="form-control" ng-class="{error:newRelation.VariantID==0 && onSave}" required>
                        <option value="0">Seçiniz</option>
                        <option ng-repeat="property in variantProperties" ng-value="property.ID">{{property.Name}}</option>
                    </select>
                </td>
                <td>
                    <select ng-model="newRelation.VariantValue" class="form-control" ng-class="{error:newRelation.VariantValue==0 && onSave}" required>
                        <option value="0">Tümü</option>
                        <option ng-repeat="opt in getOptionList(newRelation.VariantID)" ng-value="opt.ID">{{opt.Name}}</option>
                    </select>
                </td>
                <td><input type="text" class="form-control text-right" name="Price" ng-model="newRelation.Price" maxlength="6" /></td>
                <td>
                    @Html.ButtonFor("Ekle", "btn-sm btn-info", "plus", "ng-click='saveRelation(newRelation)'")
                </td>
            </tr>
        </tbody>
    </table>
</div>

WebMarket/WebMarket.Admin/Views/Variant/_VariantSelections.cshtml
@using WebMarket.Admin.Helper
<div class="variant-selections">
    <p class="error-panel text-danger" ng-hide="variantSelections.length>0">
        Bu öğe/ürün için henüz varyant kombinasyonu seçmediniz!
    </p>

    <input type="text" class="form-control txt-selection-filter" ng-model="fname" maxlength="20" placeholder="Ara.." ng-show="variantSelections.length>8" />
    <table class="mt20 table variant-selections" ng-show="variantSelections.length>0">
        <thead>
            <tr>
                <th width="30%">Kombinasyon</th>
                <th width="20%">Stok</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="selection in variantSelections | filter:{Name:fname}">
                <td class="name">{{selection.Name}}</td>
                <td><input type="text" class="form-control text-right validate" name="Stock" ng-model="selection.Stock" maxlength="10" /></td>
                <td>
                    @Html.ButtonFor("Güncelle", "btn-sm btn-success", "check", "ng-click='updateVariantSelection(selection)'")
                    @Html.ButtonFor("Sil", "ml10 btn-sm btn-danger", "remove", "ng-click='removeVariantSelection(selection)'")
                </td>
            </tr>
            <tr ng-show="(variantSelections | filter:{Name:fname}).length==0">
                <td colspan="3" class="text-red">Aramanıza uygun sonuç bulunamadı!</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th width="15%" ng-repeat="property in selectionProps">{{property.name}}</th>
                <th width="15%">Stok</th>
                <th>İşlemler</th>
            </tr>
        </thead>
        <tbody>
            <tr class="variant-selection-row">
                <td ng-repeat="property in selectionProps">
                    <select ng-model="newSelection.props[property.id]" class="form-control validate sbx-check">
                        <option value="0">Seçiniz</option>
                        <option ng-repeat="opt in property.options" ng-value="opt.id">{{opt.name}}</option>
                    </select>
                </td>
                <td><input type="text" class="form-control text-right validate" name="Stock" ng-model="newSelection.Stock" maxlength="10" /></td>
                <td>
                    @Html.ButtonFor("Yeni Kombinasyon Ekle", "btn-info", "plus", "ng-click='saveVariantSelection(newSelection)'")
                </td>
            </tr>
        </tbody>
    </table>
</div>