WebMarket/WebMarket.Admin/Controllers/StoreItemController.cs
using System.Web.Mvc;
using System.Linq;
using Aware;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Model;
using Aware.Util;
using WebMarket.Admin.Models.ModelBinder;
using Aware.ECommerce.Manager;
using Aware.ECommerce.Search;
using Aware.Util.Model;

namespace WebMarket.Admin.Controllers
{
    public class StoreItemController : BaseController
    {
        private readonly IUploadItemManager _uploadManager;
        private readonly IStoreItemService _itemService;

        public StoreItemController(IStoreItemService itemService,IUploadItemManager uploadManager)
        {
            _itemService = itemService;
            _uploadManager = uploadManager;
        }

        public ActionResult Index([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams)
        {
            var result = _itemService.GetItems(searchParams, CurrentUser.CustomerID);
            return View("Index", result);
        }

        public ActionResult AllItems([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams)
        {
            return Index(searchParams);
        }

        public ActionResult Detail(int id, int storeID = 0, Result result = null)
        {
            var model = _itemService.GetDetailModel(CurrentUser.CustomerID, id);
            if (model != null)
            {
                if (id <= 0 && storeID > 0)
                {
                    var store = model.StoreList.FirstOrDefault(i => i.ID == storeID);
                    model.StoreItem.Store = store;
                    model.StoreItem.StoreID = storeID;
                }
                model.SaveResult = result;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Detail(StoreItem model)
        {
            var result = Result.Error(Resource.General_Error);
            if (ModelState.IsValid)
            {
                var isNew = model.ID == 0;
                result = _itemService.Save(model);
                if (result.OK && isNew)
                {
                    var item = result.ValueAs<StoreItem>();
                    model = _itemService.Get(CurrentUser.CustomerID, item.ID);
                    return RedirectToRoute(Helper.RouteNames.StoreItemDetailRoute,
                        new { storename = model.Store.DisplayName.ToSeoUrl(), productname = model.Product.Name.ToSeoUrl(), id = model.ID });
                }
            }
            return Detail(model.ID, model.StoreID, result);
        }

        [HttpPost]
        public JsonResult QuickUpdate(int itemID, decimal price, decimal listPrice, decimal stock)
        {
            var result = _itemService.QuickUpdateItem(itemID, price, listPrice, stock);
            return ResultValue(result);
        }

        [HttpPost]
        public JsonResult ImportItems(int storeID)
        {
            var result = _uploadManager.UploadStoreItems(HttpContext.Request, storeID);
            return ResultValue(result);
        }
    }
}

WebMarket/WebMarket.Admin/Views/StoreItem/Detail.cshtml
@using Aware.ECommerce.Enums
@using WebMarket.Admin.Helper
@using Aware.Util;
@using Aware.Util.Enums
@using Aware.Util.Model
@using Aware.Util.View
@model Aware.ECommerce.Model.StoreItemDetailModel

@{
    ViewBag.Title = "Market Ürünü";
    ViewBag.SaveResult = Model != null ? Model.SaveResult : null;
    TempData["ActivePage"] = 4;

    var storeItem = Model != null ? Model.StoreItem : null;
    if (storeItem != null && storeItem.Product != null && storeItem.Store != null)
    {
        ViewBag.Title = storeItem.Store.DisplayName + " / ";
        ViewBag.Title += storeItem.Product.ID > 0 ? storeItem.Product.Name + " Ürünü" : "Yeni Ürün";
    }
}

<section class="container-fluid item-detail">
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-th"></i></div>
                <div class="card-content">
                    <h2 class="card-title">@ViewBag.Title</h2>

                    @if (storeItem != null)
                    {
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab_general" data-toggle="tab">DETAY</a></li>
                                @if (storeItem.HasVariant)
                                {
                                    <li class=""><a href="#tab_variants" data-toggle="tab">VARYANT ÖZELLİKLER</a></li>
                                    <li class=""><a href="#tab_variant_selections" data-toggle="tab">VARYANT KOMBİNASYONLAR</a></li>
                                }
                            </ul>
                            <div class="col-md-12 tab-content" ng-app="adminApp" ng-controller="variantCtrl">
                                <div class="tab-pane active storeitem-detail-dialog" id="tab_general">
                                    <div class="col-md-6">
                                        @using (Html.BeginForm("Detail", "StoreItem", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                                        {
                                            var storeList = Model.StoreList.Select(i => new Item(i.ID, i.DisplayName)).ToList();
                                            var itemFields = new FieldHelper(FieldDirection.Horizantal, 3);

                                            itemFields.Label("#ID", storeItem.ID.ToString(), "viewable");
                                            itemFields.Select("Market", "StoreID", storeList, (int)storeItem.StoreID, "store-single-selector validate sbx-check");

                                            itemFields.Text("ProductID", "Ürün", storeItem.Product.Name, "product-selector validate sbx-check", 50).SetAttr("data-id='" + storeItem.ProductID + "'")
                                                .SetAffix("<a title='Ürünü Görüntüle' target='_blank' class='text-maroon' href='" + Url.Action("Detail", "Product", new { name = storeItem.Product.Name.ToSeoUrl(), id = storeItem.ProductID }) + "'><i class='fa fa-eye'></i></a>");
                                            itemFields.Number("SalesPrice", "Satış Fiyatı", storeItem.SalesPrice.ToString(), "validate dec-pnumber", 10).SetAffix("<i class='fa fa-turkish-lira'></i>");
                                            itemFields.Number("ListPrice", "Liste Fiyatı", storeItem.ListPrice.ToString(), "validate dec-pnumber", 10).SetAffix("<i class='fa fa-turkish-lira'></i>");
                                            itemFields.Number("Stock", "Stok", storeItem.Stock.ToString("N"), "validate", 6).SetAffix(storeItem.Product.UnitDescription.Short(2, ""));

                                            itemFields.BtnGroup("Durum", "Status", Model.StatusList, ((int)storeItem.Status).ToString());
                                            itemFields.BtnGroup("Satışa Açık", "IsForSale", Model.YesNoList, storeItem.IsForSale ? "1" : "0").SetAsBool();
                                            itemFields.BtnGroup("Varyant Kullan", "HasVariant", Model.YesNoList, storeItem.HasVariant ? "1" : "0").SetAsBool();

                                            @Html.Hidden("ID", storeItem.ID)
                                            @Html.Partial("_FieldHelper", itemFields)

                                            <hr />
                                            <div class="text-right">
                                                @if (storeItem.ID > 0)
                                                {
                                                    @Html.ButtonFor("Kaldır", "mr10 btn-danger btn-remove-item", "remove")
                                                }
                                                @Html.ButtonFor("Kaydet", "btn-success btn-save")
                                            </div>
                                        }
                                    </div>
                                    <div class="mb20 col-md-6">
                                        @Html.ImageFor("", storeItem.Product.DefaultImage.Path, "", "img-responsive")
                                    </div>
                                </div>

                                @if (storeItem.ID > 0 && storeItem.HasVariant)
                                {
                                    var relationModel = new Aware.ECommerce.Model.VariantRelationViewModel() { RelationID = storeItem.ID, RelationType = (int)RelationTypes.StoreItem };
                                    <div class="tab-pane" id="tab_variants">
                                        <div class="col-md-12">
                                            <p class="mb20">
                                                Bu alanda ürününüze varyant özellikler ekleyebilirsiniz. Varyant özellikler ürünün varyasyonlarını belirler. Örneğin "Renk"
                                                skalasında bir tişört Mavi, Beyaz, Yeşil olabilirken aynı zamanda "Beden" skalasında S, M, L, XL opsiyonlarına sahip olabilir.
                                            </p>
                                            @Html.Partial("~/Views/Variant/_VariantRelations.cshtml", relationModel)
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="tab_variant_selections">
                                        <div class="col-md-12">
                                            <p class="mb20">
                                                Bu alanda ürününüz için belirlediğiniz varyant özellikler için stok kombinasyonları belirleyebilirsiniz. Örneğin
                                                "Renk" ve "Beden" varyantları için [Sarı, XL], [Yeşil, M] gibi kombinasyonlar tanımlayabilir ve her biri için ayrı stok tanımlamaları yapabilirsiniz.
                                                Ancak [Kırmızı, XXL] seçimi için stok tanımı yapmak istemezseniz bu kombinasyonu eklemenize gerek yok. Bu durumda stok takibi varyant üzerinden değil
                                                ürün üzerinden yapılacaktır.
                                            </p>

                                            @Html.Partial("~/Views/Variant/_VariantSelections.cshtml")
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    }
                    else
                    {
                        <hr />
                        <div class="no-result-found">
                            <i class="fa fa-warning"></i>
                            <h4>Ürün Bulunamadı!</h4>
                            <p class="description">Böyle bir ürün yok ya da görüntüleme yetkiniz bulunmuyor!</p>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

@section pageheader{
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.3/angular.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.3/angular-resource.min.js" type="text/javascript"></script>
    @Scripts.Render("~/resource/js/angularjs")
    <script src="~/resource/js/storeitem.js"></script>

    <style>
        .product-selector.selecto-wrap { z-index: 3; }
        .product-selector.selecto-wrap .txt, .store-selector.selecto-wrap .txt { border: 0 none; background: transparent; margin: 0; padding: 0; height: 100%; outline: none; }
        .variant-selections tr td.name { font-weight: 600; color: #199ace; font-size: 15px; font-style: italic; }
        .txt-selection-filter { width: 306px; }
    </style>
}

WebMarket/WebMarket.Admin/Views/StoreItem/Index.cshtml
@using Aware.ECommerce.Model
@using Aware.ECommerce.Search
@using Aware.Util
@using Aware.Util.Enums
@using Aware.Util.Model
@using Aware.Util.View
@using WebMarket.Admin.Helper
@using Constants = Aware.ECommerce.Util.Constants
@model StoreItemListModel
@{
    ViewBag.Title = "Ürünlerim";
    TempData["ActivePage"] = 4;

    Store store = null;
    var searchResult = Model != null ? Model.SearchResult : null;
    var searchParams = searchResult != null ? searchResult.SearchParams as ItemSearchParams : new ItemSearchParams();
    if (searchParams.StoreIDs != null && searchParams.StoreIDs.Count() == 1)
    {
        store = Model.Stores.FirstOrDefault(s => s.ID == searchParams.StoreIDs.FirstOrDefault());
    }

    if (store != null)
    {
        ViewBag.Title = string.Format("{0} Ürünleri", store.DisplayName);
    }
    store = store ?? new Store() { DisplayName = "magaza" };
}

<section class="container-fluid item-list">
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-table"></i></div>
                <div class="card-content">
                    <h2 class="card-title">
                        @ViewBag.Title
                        <a href="@Url.RouteUrl(RouteNames.StoreNewItemRoute,new {storename=store.DisplayName.ToSeoUrl(),storeID=store.ID})" class="btn btn-info btn-round btn-fab btn-fab-mini ml20" title="Yeni Ekle"><i class="fa fa-plus"></i></a>
                    </h2>
                    <div style="position: absolute;right: 15px;top: 15px; z-index: 100;">
                        <a data-toggle="collapse" href="#Actions" class="btn btn-info">
                            <i class="fa fa-gear"></i>  <span>İşlemler <i class="ml10 fa fa-caret-down"></i></span>
                        </a>
                        <div class="collapse" id="Actions" style="background: #fff;box-shadow: 0 3px 10px -1px #aaa;">
                            <ul class="nav">
                                <li routerlinkactive="active">
                                    <a href="javascript:void(0)" class="btn-import-data excell"><i class="fa fa-download"></i> Excelden Aktar</a>
                                </li>
                                <li routerlinkactive="active" class="">
                                    <a href="javascript:void(0)" class="btn-import-data"><i class="fa fa-download"></i> Şablondan Aktar</a>
                                </li>
                                <li routerlinkactive="active">
                                    <a href="javascript:void(0)" class="btn-export-modal"><i class="fa fa-share"></i> Şablona Aktar</a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    @if (store != null && store.ID > 0)
                    {
                        @Html.Hidden("StoreID", store.ID)
                    }

                    @if (searchResult != null && searchResult.HasResult && searchResult.Success)
                    {
                        @Html.PagingInfo(searchResult, "üründen")

                        <div class="fl table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th width="5%">#ID</th>
                                        <th colspan="2">Ürün</th>
                                        <th>Kategori</th>
                                        <th>Satış fiyatı</th>
                                        <th>Liste fiyatı</th>
                                        <th>Stok</th>
                                        <th width="5%">Durum</th>
                                        <th>İşlemler</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in searchResult.Results)
                                    {
                                        var product = item.Product;
                                        var stockInfo = item.Stock != -1 ? item.Stock.ToString("0") + " " + product.UnitDescription.Short(2, "") : "Sınırsız";

                                        <tr data-item-id="@item.ID">
                                            <td>@item.ID</td>
                                            <td style="width: 5%;">
                                                @Html.ImageFor("", product.DefaultImage.Path, product.Name, "image item-image", product.Name)
                                            </td>
                                            <td width="15%" class="td-name"><a href="@Url.Action("Detail", "Product", new {name = product.Name.ToSeoUrl(), id = item.ProductID})" target='_blank'>@product.Name</a></td>
                                            <td>@Model.GetCategoryInfo(product.CategoryID)</td>
                                            <td class="sales-price">@Html.ToPrice(item.SalesPrice)</td>
                                            <td class="list-price">@Html.ToPrice(item.ListPrice)</td>
                                            <td class="stock @(item.Stock == -1 ? "infinite" : "")">@stockInfo </td>
                                            <td class="text-center">@Html.StatusFor(item.Status) </td>
                                            <td>
                                                <button class="btn btn-sm btn-info btn-show-stock" title="Hızlı Güncelle" data-stock="@item.Stock.DecToStr()" data-price="@item.SalesPrice.DecToStr()" data-list-price="@item.ListPrice.DecToStr()">
                                                    <i class="fa fa-edit"></i>
                                                </button>
                                                <a href="@Url.Action("Detail", new {productname = product.Name.ToSeoUrl(), storename = Model.GetStoreInfo(item.StoreID).ToSeoUrl(), id = item.ID})" class="btn btn-sm btn-success" title="İncele"><i class="fa fa-eye"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                        <div class="fr mt10 mb10 store-item-pager"></div>
                    }
                    else
                    {
                        <hr />
                        <div class="no-result-found">
                            <i class="fa fa-warning"></i>
                            <h4>Listelenecek Ürün Bulunamadı!</h4>
                            <p class="description">Arama kriterlerinizi gözden geçirin.</p>
                        </div>
                    }
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-filter"></i></div>
                <div class="card-content search-panel">
                    <h2 class="card-title">Filtrele</h2>

                    @using (Html.BeginForm("Index", "StoreItem", FormMethod.Get, new { enctype = "multipart/form-data" }))
                    {
                        var storeData = Model.Stores.Select(i => new Item(i.ID, i.DisplayName)).ToList();
                        var categoryData = Model.Categories.Select(i => new Item(i.ID, i.Name)).ToList();

                        var selectedStores = searchParams.StoreIDs != null ? string.Join(",", searchParams.StoreIDs) : string.Empty;
                        var selectedCategories = string.Join(",", searchParams.CategoryIDs);
                        var priceRange = Html.GetRange(searchParams.Price);
                        var stockRange = Html.GetRange(searchParams.Stock);

                        var filterFields = new FieldHelper();
                        filterFields.Text("ids", "ID/ler", searchParams.IDsString, "item-id", 200);
                        filterFields.Text("q", "Ürün Adı", searchParams.Keyword, "name");
                        filterFields.Select("Market", "sid", storeData, selectedStores, "store-selector", "", true);
                        filterFields.Select("Kategori", "cid", categoryData, selectedCategories, "category-selector");
                        filterFields.Select("Durum", "st", Html.GetStatusList(), (int)searchParams.Status.GetValueOrDefault(), "status-selector");

                        <div class="box-body">
                            @Html.Partial("_FieldHelper", filterFields)
                            <div class="form-group">
                                <label>Fiyat Aralığı</label>
                                <div>
                                    @Html.Hidden("price", searchParams.Price)
                                    <input type="text" class="form-control txt-range price-from" value="@priceRange.Key" placeholder="0 TL" />
                                    <span> - </span>
                                    <input type="text" class="form-control txt-range price-to" value="@priceRange.Value" placeholder="9999.00 TL" />
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Hidden("stock", searchParams.Stock)
                                <label>Stok Durumu</label>
                                <div>
                                    <input type="text" class="form-control txt-range stock-from" placeholder="0" value="@stockRange.Key" />
                                    <span> - </span>
                                    <input type="text" class="form-control txt-range stock-to" placeholder="9999" value="@stockRange.Value" />
                                </div>
                                <div class="mt10">
                                    <label class="field-cbx unlimited-stock"><input type="checkbox" class="cbx" @(searchParams.IncludeUnlimitedStock ? "checked='checked'" : "") /> Sınırsız stoklu ürünleri dahil et</label>
                                </div>
                                <div>
                                    <label class="field-cbx for-sale"><input type="checkbox" class="cbx" @(searchParams.OnlyForSale ? "checked='checked'" : "") /> Sadece satışa açık ürünler</label>
                                </div>
                            </div>

                            <hr />
                            <div class="box-footer">
                                @Html.ButtonFor("Temizle", "mr10 btn-danger btn-clean-filter", "trash")
                                @Html.ButtonFor("Ara", "btn-success btn-search", "search")
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>

        @Html.Partial("_ExportImportModal")
    </div>
</section>

@section pageheader
{
    <script src="~/resource/js/storeitem.js"></script>
    <script src="~/resource/js/bootstrap-slider.js"></script>

    @if (searchResult != null)
    {
        <script type="text/javascript">
            $(document).ready(function () {
                setPager('.store-item-pager', '@searchResult.SearchParams.Size', '@searchResult.TotalSize');
            });
        </script>
    }

    <style>
        .txt-range { width: 40%; display: inline-block; margin: 0px 5px; }
        .field-cbx { font-weight: 400; margin-bottom: 8px; margin-left: 5px; }
        .field-cbx .cbx { vertical-align: top; margin-top: 5px; }
    </style>
}

WebMarket/WebMarket.Admin/Views/StoreItem/_ExportImportModal.cshtml
@using Aware.Util
@using Aware.Util.Enums
@using Aware.Util.View
@using WebMarket.Admin.Helper
@using WebMarket.Admin.Models

<div id="importItemsModal" class="modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Ürün Aktarma Sihirbazı</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("ImportItems", "StoreItem", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <fieldset>
                        @Html.Hidden("StoreID", 0)
                        <span class="db mb20 text-navy">
                            Bu sihirbazı kullanarak ürünlerinizi uygun formattaki bir <span class="file-type"></span> dosyasından hızlıca yükleyebilirsiniz.
                            Örnek dosya formatı için <a href="/file/sampleformat">tıklayınız</a>.
                        </span>

                        <div class="fileUpload">
                            <span class="btn btn-flat btn-danger">Dosya Seç</span>
                            <span class="fileUploaded input">Dosya seçilmedi..</span>
                            <input type="file" id="uploaditem" name="uploaditem" class="upload" data-extension="" />
                        </div>
                        <span class="db mt10" style="font-style: italic;font-size: 12px;">Sadece <span class="ext-type"></span> uzantılı dosyalar desteklenmektedir.</span>
                    </fieldset>
                }
            </div>
            <div class="modal-footer">
                @Html.ButtonFor("Aktarımı Başlat", "btn-success btn-start-import", "check", "disabled='disabled'")
            </div>
        </div>
    </div>
</div>

<div id="exportTemplateModal" class="modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Ürünleri Şablona Aktar</h4>
            </div>
            <div class="modal-body" style="max-height: 360px; overflow-y: scroll;">

            </div>
            <div class="modal-footer">
                @Html.ButtonFor("Aktarımı Başlat", "btn-success btn-export-template", "check", "disabled='disabled'")
            </div>
        </div>
    </div>
</div>

<div id="updateStockModal" class="modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title item-name">Ürün Güncelle</h4>
            </div>
            <div class="modal-body">
                @{
                    var stockTitle = "Ürün Stoğu <i class='fa fa-info-circle' title='Ürün stoğunu sınırsız yapmak için ürün stoğunu -1 olarak belirtin'></i>";
                    var fieldHelper = new FieldHelper(FieldDirection.Horizantal,3);

                    fieldHelper.Number("Price", "Satış Fiyatı", string.Empty, "validate dec-pnumber").SetAffix("<i class='fa fa-turkish-lira'></i>");
                    fieldHelper.Number("ListPrice", "Liste Fiyatı", string.Empty, "validate dec-pnumber").SetAffix("<i class='fa fa-turkish-lira'></i>");
                    fieldHelper.Number("Stock", stockTitle, string.Empty, "validate dec-number item-stock").SetAffix("<span class='item-unit'>ad</span>");
                }

                @Html.Partial("_FieldHelper", fieldHelper)
            </div>
            <div class="modal-footer">
                @Html.ButtonFor("Kaydet", "btn-success btn-save-stock", "ok")
            </div>
        </div>
    </div>
</div>

WebMarket/WebMarket.Admin/Views/StoreItem/_ExportItems.cshtml
@using Aware.Util
@using Aware.Util.Enums
@using WebMarket.Admin.Helper
@model Aware.Search.SearchResult<Aware.ECommerce.Model.StoreItem>

@if (Model != null && Model.HasResult)
{
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <td>@Html.CheckBox("item", true)</td>
                <th colspan="2">Ürün</th>
                <th>Satış fiyatı</th>
                <th>Liste fiyatı</th>
                <th>Stok</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Results)
            {
                var product = item.Product;
                <tr data-item-id="@item.ID">
                    <td>@Html.CheckBox("item",true)</td>
                    <td style="width:5%;">@Html.ImageFor("", product.DefaultImage.Path, product.Name, "image", product.Name)</td>
                    <td class="name">@product.Name</td>
                    <td>@item.SalesPrice.ToPrice()</td>
                    <td>@item.ListPrice.ToPrice()</td>
                    <td>@item.Stock.ToString("0")</td>
                    <td class="text-center">
                        @(item.Status==Statuses.Active?"Aktif":"Pasif")
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning">
        <span><i class="fa fa-comment-o"></i> Aktarım yapılacak herhangi bir ürün bulunamadı!</span>
    </div>
}