WebMarket/WebMarket/Models/OperationResult.cs
namespace WebMarket.Models
{
    public class OperationResult
    {
        public int ResultCode { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string IconClass { get; set; }

        public OperationResult(int code,string title,string iconCss,string content)
        {
            ResultCode = code;
            Title = title;
            IconClass = iconCss;
            Content = content;
        }
    }
}

WebMarket/WebMarket/Controllers/CampaignController.cs
using System.Web.Mvc;
using Aware.ECommerce.Interface;

namespace WebMarket.Controllers
{
    public class CampaignController : BaseController
    {
        private readonly ICampaignService _campaignService;

        public CampaignController(ICampaignService campaignService)
        {
            _campaignService = campaignService;
        }

        public ActionResult Index()
        {
            var model = _campaignService.GetActiveCampaigns();
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var model = _campaignService.GetActiveCampaign(id);
            return View(model);
        }
    }
}

WebMarket/WebMarket/Controllers/HelperController.cs
using System.Web.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Aware.Notification;
using Aware.Mail;
using Aware.Authenticate;
using Aware.Language;

namespace WebMarket.Controllers
{
    public class HelperController : BaseController
    {
        private readonly INotificationService _notificationService;
        private readonly IMailService _mailService;
        private readonly ISessionManager _sessionManager;
        private readonly ILanguageService _languageService;

        public HelperController(INotificationService notificationService, IMailService mailService,ISessionManager sessionManager, ILanguageService languageService)
        {
            _notificationService = notificationService;
            _mailService = mailService;
            _languageService = languageService;
            _sessionManager = sessionManager;
        }

        [HttpPost]
        public JsonResult CheckNotification()
        {
            var notification = _notificationService.GetUserNotification(CurrentUserID);
            var success = notification != null ? 1 : 0;
            return Json(new { success, notification }, JsonRequestBehavior.DenyGet);
        }

        public ActionResult SelectRegion()
        {
            return View();
        }

        public ActionResult DynamicPage(int pageID)
        {
            var model = new Tuple<int, string, string>(pageID, "Deneme", "Deneme İçerik");
            return View(model);
        }

        public JsonResult MailTest()
        {
            _mailService.SendWelcomeMail("osman.sokuoglu@gmail.com", "Osman Sokuoğlu", "#");
            return Json("Gönderildi", JsonRequestBehavior.AllowGet);
        }

        public ActionResult LanguageList()
        {
            var languageList = _languageService.GetCachedLanguages();
            if (languageList != null && languageList.Any())
            {
                var defaultLanguage = _sessionManager.GetCurrentLanguage();
                languageList = languageList.Where(i => i.Abbreviate != defaultLanguage).ToList();
            }
            return PartialView(languageList);
        }

        public ActionResult ChangeLanguage(string lang)
        {
            _sessionManager.SetCurrentLanguage(lang);
            var returnUrl = Request.UrlReferrer != null ? Request.UrlReferrer.PathAndQuery : "/";
            return Redirect(returnUrl);
        }

        [HttpPost]
        public JsonResult RefreshRegion(int regionID)
        {
            var success = _sessionManager.SetCurrentRegion(regionID) ? 1 : 0;
            return Json(new { success }, JsonRequestBehavior.DenyGet);
        }
    }
}

WebMarket/WebMarket/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using Aware.ECommerce;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Manager;
using Aware.ECommerce.Model;
using Aware.ECommerce.Search;
using Aware.ECommerce.Util;
using Aware.Util;
using Aware.Util.Model;
using WebMarket.Helper;
using WebMarket.Models;
using Aware.Util.Enums;
using WebMarket.Filters;
using WebMarket.Models.ModelBinder;

namespace WebMarket.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductSearchManager _productSearchManager;
        private readonly ICategoryService _categoryService;
        private readonly IPropertyService _propertyService;
        private readonly IFavoriteService _favoriteService;
        private readonly IVariantService _variantService;
        private readonly IApplication _application;
        private readonly IStoreService _storeService;

        private readonly object _lockThis = new object();

        public ProductController(IProductSearchManager productSearchManager, IStoreService storeService, ICategoryService categoryService, IPropertyService propertyService,
            IFavoriteService favoriteService, IApplication application, IVariantService variantService)
        {
            _productSearchManager = productSearchManager;
            _storeService = storeService;
            _categoryService = categoryService;
            _propertyService = propertyService;
            _favoriteService = favoriteService;
            _application = application;
            _variantService = variantService;
        }

        [RegionSelection]
        public ActionResult Index([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams)
        {
            return Search(searchParams, true);
        }

        public ActionResult Search([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams, bool asView = false)
        {
            searchParams.SetPaging(0, 36).WithAggs().WithCount();
            var searchResult = _productSearchManager.Search(searchParams, _storeService.GetRegionStores());

            var model = new ProductSearchViewModel()
            {
                SearchResult = searchResult,
                FavoriteProducts = _favoriteService.GetUserFavorites(CurrentUserID),
                ForStoreDetail = !asView,
                FilterDirection = asView && searchResult.HasAggregation ? LayoutDirection.Vertical : LayoutDirection.Horizantal,
                AllowCompare = _application.Site.AllowProductCompare
            };

            if (asView)
            {
                return View("Index", model);
            }
            return PartialView("_ProductListView", model);
        }

        public JsonResult LoadNextPage([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams)
        {
            searchParams.WithCount();
            var searchResult = _productSearchManager.Search(searchParams, _storeService.GetRegionStores());

            if (searchResult != null && searchResult.Success)
            {
                var completed = searchResult.HasMore ? 0 : 1;
                var model = new ProductSearchViewModel()
                {
                    SearchResult = searchResult,
                    AllowCompare = _application.Site.AllowProductCompare
                };

                var html = this.RenderPartialView("_ProductListView2", model);
                return Json(new { success = 1, html, completed }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = 0 }, JsonRequestBehavior.AllowGet);
        }

        [RegionSelection]
        public ActionResult Detail(int id, int? storeID)
        {
            var model = new ProductViewModel
            {
                Product = _productSearchManager.GetProductDetail(id, storeID),
                FavoriteProducts = _favoriteService.GetUserFavorites(CurrentUserID),
                DisplayComments = _application.Site.DisplayComments,
                AllowCompare = _application.Site.AllowProductCompare,
                AllowSoialShare = _application.Site.AllowSocialShare,
                ShowInstallments = _application.Site.ShowProductInstallments && _application.Order.PosList != null && _application.Order.PosList.Any()
            };

            if (model.Product != null && model.Product.Properties != null && model.Product.Properties.Any())
            {
                model.ArrangeProperties(_propertyService.GetAllCachedProperties());
            }
            return View("Detail", model);
        }

        [Aware.Util.Filter.Authorize]
        public ActionResult MyFavorites([ModelBinder(typeof(ItemSearchBinder))] ItemSearchParams searchParams)
        {
            searchParams.OnlyFavorites = CurrentUserID > 0;
            searchParams.UserID = CurrentUserID;
            return Search(searchParams, true);
        }

        public ActionResult Comments(int id, int page = 1)
        {
            var model = _propertyService.GetProductCommentStats(id, CurrentUserID, page);
            model.IsPartial = false;
            return View("ProductComments", model);
        }

        public JsonResult SearchProducts(string keyword)
        {
            lock (_lockThis)
            {
                var searchParams = new ItemSearchParams(keyword, 0, 10) { SearchCategories = true };
                var model = _productSearchManager.Search(searchParams, _storeService.GetRegionStores());
                var html = this.RenderPartialView("_SearchResultPreview", model);
                return Json(new { html }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult GetCategoryHierarchy(int parentID)
        {
            var hierarchy = _categoryService.GetCategoryHierarchy(parentID);
            var html = Util.DrawProductHierarchicalCategories(hierarchy);
            return Json(new { success = 1, html }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetSimilarItems(int storeID, int categoryID, int productID)
        {
            var searchParams = new ItemSearchParams(string.Empty, 0, 16);
            searchParams.WithStore(storeID).WithCategory(categoryID);

            var result = _productSearchManager.Search(searchParams, _storeService.GetRegionStores());
            if (!result.Success || !result.HasResult) return Json(new { success = 0 }, JsonRequestBehavior.AllowGet);

            var products = result.Results.Where(i => i.ID != productID).ToList();
            if (!products.Any()) return Json(new { success = 0 }, JsonRequestBehavior.AllowGet);

            var slider = new MultiSliderModel("similarItems")
            {
                Products = products,
                ItemCount = 4,
                Title = "Benzer Ürünler"
            };

            var html = this.RenderPartialView("_MultiSlider", slider);
            return Json(new { success = 1, html }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetProductCommentStats(int productID, string productName)
        {
            var model = _propertyService.GetProductCommentStats(productID, CurrentUserID);
            if (model != null)
            {
                model.Title = productName;
                model.IsPartial = true;

                var html = this.RenderPartialView("_ProductCommentView", model);
                var success = !string.IsNullOrEmpty(html);
                return Json(new { success, html, cc = model.CommentCount, avg = model.RatingAverage }, JsonRequestBehavior.DenyGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult SaveComment(int productID, string title, string value, int rating)
        {
            var model = new Comment
            {
                Title = title,
                Value = value,
                Rating = rating,
                RelationType = (int)RelationTypes.Product,
                RelationID = productID,
                OwnerID = CurrentUserID,
                OwnerName = CurrentUser.Name.AsCommentOwner()
            };

            var result = _propertyService.SaveComment(model);
            return ResultValue(result);
        }

        [RegionSelection]
        public ActionResult CompareProducts()
        {
            ProductSearchViewModel model = null;
            var compareCookie = _application.WebHelper.GetCookie("compare-list");
            if (compareCookie != null && !string.IsNullOrEmpty(compareCookie.Value))
            {
                var productIDs = compareCookie.Value.Split(",").Select(i => i.Int()).ToList();
                var searchParams = new ItemSearchParams(string.Empty, 0, productIDs.Count) { IDs = productIDs };
                model = new ProductSearchViewModel()
                {
                    SearchResult = _productSearchManager.Search(searchParams, _storeService.GetRegionStores())
                };
                ViewBag.PropertyData = _propertyService.GetAllCachedProperties();
            }
            return View("CompareProducts", model);
        }

        [HttpPost]
        public JsonResult GetComparedProductsInfo(string productIDs)
        {
            if (!string.IsNullOrEmpty(productIDs))
            {
                var ids = productIDs.Trim().Split(",").Select(i => i.Int()).ToList();
                var searchParams = new ItemSearchParams(string.Empty, 0) { IDs = ids };
                var searchResult = _productSearchManager.Search(searchParams, _storeService.GetRegionStores());

                if (searchResult != null && searchResult.HasResult)
                {
                    var items = searchResult.Results.Select(i => new Item(i.ID, i.Name, string.Empty, i.DefaultImage.Path)).ToList();
                    return Json(new { success = 1, items }, JsonRequestBehavior.DenyGet);
                }
            }

WebMarket/WebMarket/Controllers/StoreController.cs
using System.Web.Mvc;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Util;
using WebMarket.Filters;

namespace WebMarket.Controllers
{
    [RegionSelection]
    public class StoreController : BaseController
    {
        private readonly IStoreService _storeService;
        public StoreController(IStoreService storeService)
        {
            _storeService = storeService;
        }

        public ActionResult Index()
        {
            var model = _storeService.GetRegionStores();
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var model = _storeService.GetRegionStore(id,true);
            if (model == null || !model.HasRegion(UserRegionID) || model.ServiceRegions == null)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

WebMarket/WebMarket/Views/Shared/_CarouselSliderView.cshtml
@model Aware.Util.Model.Slider
@{
    var isMain = (Model.ID == "main-carousel");
}

@if (Model != null && Model.Items.Any())
{
    <div id="@Model.ID" class="mt20 carousel slide @Model.Css" data-interval="@Model.SwitchTime" data-ride="carousel" data-type="@(isMain?"single":"multi")">
        @if (isMain)
        {
            <ol class="carousel-indicators">
                @for (var i = 0; i < Model.Items.Count; i++)
                {
                    <li data-target="#@Model.ID" data-slide-to="@i" class="@(i==0 ? "active":"")"></li>
                }
            </ol>
        }

        <div class="carousel-inner">
            @foreach (var item in Model.Items)
            {
                <div class="@(Model.Items.IndexOf(item) == 0  ? "active" : "") item">
                    @Html.Raw(item.Value)
                </div>
            }
        </div>

        @if (Model.Items.Count() > 1)
        {
            <a class="carousel-control left" href="#@Model.ID" data-slide="prev">
                <i class="fa fa-2x fa-angle-left"></i>
            </a>

            <a class="carousel-control right" href="#@Model.ID" data-slide="next">
                <i class="fa fa-2x fa-angle-right"></i>
            </a>
        }
    </div>
}

WebMarket/WebMarket/Views/Shared/_FieldHelper.cshtml
@using Aware.Util
@using Aware.Util.Enums
@model Aware.Util.View.FieldHelper
@foreach (var field in Model.Fields)
{
    <div class="form-group @field.ParentCss">
        @if (field.HasAffix || Model.Direction == FieldDirection.Inline)
        {
            if (Model.Direction != FieldDirection.Inline)
            {
                <label for="@field.ID" class="@Model.TitleCss">@field.Title</label>
            }

            <div class="@(field.HasAffix?"input-group":"") @(Model.Direction== FieldDirection.Horizantal ? "col-sm-"+(12 - Model.TitleColumnCount)+" horizantal":"")">
                @Html.Partial("_Field", field)
            </div>
        }
        else if (Model.Direction == FieldDirection.Horizantal)
        {
            <label for="@field.ID" class="@Model.TitleCss">@field.Title</label>
            <div class="col-sm-@(12 - Model.TitleColumnCount)">
                @Html.Partial("_Field", field)
            </div>
        }
        else if (field.Type != FieldType.CheckBox)
        {
            <label for="@field.ID" class="@Model.TitleCss">@field.Title</label>
            @Html.Partial("_Field", field)
        }
        else
        {
            @Html.Partial("_Field", field)
        }
    </div>
}

WebMarket/WebMarket/Views/Shared/_Footer.cshtml
@using Resources

<footer class="footer">
    <div class="footer-widgets">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <div class="widget widget-categories">
                        <h4 class="widget-title"><i class="fa fa-home"></i> WebMarket.com</h4>
                        <p class="mb20">
                            @Resource.Footer_AboutText
                        </p>
                    </div>
                </div>

                <div class="mb20 col-md-3 col-sm-3">
                    <div class="widget widget-categories">
                        <h4 class="widget-title"><i class="fa fa-sitemap"></i> @Resource.Footer_Interests</h4>
                        <ul>
                            <li><a href='@Url.Action("Index", "Store")'>@Resource.Stores</a></li>
                            <li><a href='@Url.Action("Index", "Campaign")'>@Resource.Campaigns</a></li>
                            <li><a href='/meyve-ve-sebze-urunleri-1'>Meyve & Sebze</a></li>
                            <li><a href='/icecek-urunleri-6'>İçecek</a></li>
                            <li><a href='/et-ve-balik-urunleri-2'>Et & Balık</a></li>
                            <li><a href='/sut-ve-kahvaltilik-urunleri-3'>Süt & Kahvaltılık</a></li>
                        </ul>
                    </div>
                </div>
                <div class="mb20 col-md-3 col-sm-3">
                    <div class="widget widget-categories">
                        <h4 class="widget-title"><i class="fa fa-support"></i> @Resource.Footer_Help</h4>
                        <ul>
                            <li><a href='@Url.Action("AboutUs", "Home")'>@Resource.AboutUs</a></li>
                            <li><a href='@Url.Action("Contact", "Home")'>@Resource.ContactUs</a></li>
                            <li><a href='@Url.Action("SSS", "Home")'>@Resource.Footer_FAQ</a></li>
                            <li><a href="#">Teslimat</a></li>
                            <li><a href="@Url.Action("MembershipAggreement", "Home")">Üyelik Sözleşmesi</a></li>
                            <li><a href="#">Gizlilik Politikası</a></li>
                            <li><a href="#">Site Haritası</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-3 col-sm-3">
                    <div class="widget widget-tag-cloud">
                        <h4 class="widget-title"><i class="fa fa-slack"></i> @Resource.Footer_SocialMedia</h4>
                        <ul class="social-icons">
                            <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="instagram"><i class="fa fa-instagram"></i></a></li>
                            <li><a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="footer-meta">
        <div class="container">
            <div class="row">

                <div class="col-sm-6">
                    <div class="mt10 copyright">Copyright @DateTime.Now.Year Aware LTD ŞTİ | All Rights Reserved</div>
                </div>
                <div class="col-sm-6">
                    <div class="payments text-right">
                        <ul>
                            <li><img src="~/resource/img/App/visa.jpg" alt=""></li>
                            <li><img src="~/resource/img/App/mastercard.jpg" alt=""></li>
                            <li><img src="~/resource/img/App/paypal.jpg" alt=""></li>
                            <li><img src="~/resource/img/App/american-express.jpg" alt=""></li>
                            <li><img src="~/resource/img/App/visa-electron.jpg" alt=""></li>
                            <li><img src="~/resource/img/App/maestro.jpg" alt=""></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</footer>

<div class="scroll-to-top" title="Başa dön">
    <i class="fa fa-angle-up"></i>
</div>
<div class="aware-toastr"></div>
@Html.Hidden("ImageCdn",Aware.Util.Config.ImageRepository)

WebMarket/WebMarket/Views/Shared/_MyAccount.cshtml
@using Resources
@model WebMarket.Models.SiteHeaderModel
<div class="dbfl hidden-xs membership @(Model.IsLoggedIn ? "account-menu" : "logout")">
    @if (!Model.IsLoggedIn)
    {
        <a href='#loginModal' data-toggle="modal" class="btn btn-black-border login"><i class="fa fa-user"></i></a>
    }
    else
    {
        <a href='#' data-toggle="modal" class="btn btn-black-border login"><i class="fa fa-user"></i></a>
        <ul>
            <li class="user">
                <span>@Resource.Hello <br>@Model.UserInfo</span>
            </li>
            <li>
                <a href='@Url.Action("Detail", "Account")'><i class="fa fa-user"></i> @Resource.Account_MyInfo</a>
            </li>
            <li>
                <a href='@Url.Action("Index", "Basket")'><i class="fa fa-shopping-cart"></i> @Resource.Basket_Title</a>
            </li>
            <li>
                <a href='@Url.Action("MyOrders", "Order")'><i class="fa fa-bars"></i> @Resource.Order_Title</a>
            </li>
            <li>
                <a href='@Url.Action("MyFavorites", "Product")'><i class="fa fa-heart"></i> @Resource.Basket_MyFavorites</a>
            </li>
            <li>
                <a href='@Url.Action("Logout", "Account")'><i class="fa fa-power-off"></i> @Resource.Account_Logout</a>
            </li>
        </ul>
    }

    @Html.Hidden("IsLoggedIn", Model.IsLoggedIn ? "true" : "false")
</div>

WebMarket/WebMarket/Views/Shared/_ProductDropView.cshtml
@model IEnumerable<Aware.ECommerce.Model.Basket>

<div class="drop-elem-wrapper">
    <div class="title"><h4>Seçiminiz : </h4></div>
    <div class="drop-elem basket-elem">Sepete At</div>

    @if (Model != null && Model.Any())
    {
        foreach (var list in Model)
        {
            <div class="drop-elem list-elem" data-list-id="@list.ID" data-list-name="@list.Name">@list.Name Listesine Ekle</div>
        }
    }

    <div class="drop-elem new-list-elem">Yeni Listeye At</div>
</div>

WebMarket/WebMarket/Views/Shared/_SiteHeader.cshtml
@using Aware.Util
@using Resources
@model WebMarket.Models.SiteHeaderModel

<div class="header">
    <div class="hidden-xs quick-menu">
        <div class="container">
            <div class="fr top-bar-right">
                <ul class="list-inline">
                    <li class="hidden-xs"><a href="/marketler">@Resource.Stores</a></li>
                    <li class="hidden-xs"><a href="/urunler">@Resource.Items</a></li>
                    <li class="hidden-xs"><a href="/kampanyalar">@Resource.Campaigns</a></li>
                    <li class="hidden-xs"><a href="@Url.Action("Index", "Basket")">@Resource.Basket_Title</a></li>
                    <li class="hidden-xs"><a href="@Url.Action("MyOrders", "Order")">@Resource.Order_Title</a></li>
                    <li class="hidden-xs"><a href="@Url.Action("MyFavorites", "Product")">@Resource.Basket_MyFavorites</a></li>

                    <li class="hidden-xs dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">@Resource.AboutUs <i class="fa fa-angle-down"></i></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href='@Url.Action("AboutUs", "Home")'>@Resource.AboutUs</a></li>
                            <li><a href='@Url.Action("SSS", "Home")'>@Resource.FAQ</a></li>
                            <li><a href='@Url.Action("Contact", "Home")'>@Resource.ContactUs</a></li>
                        </ul>
                    </li>
                    <li class="hidden-xs"><a href='@Url.Action("SelectRegion", "Helper")'>@(Model.CurrentRegion.ID > 0 ? Model.CurrentRegion.Name + " -" : "") @Resource.SelectRegion</a></li>
                </ul>
            </div>
            @Html.Action("LanguageList", "Helper")
        </div>
    </div>

    <div class="container middle">
        <div class="row" style="margin: 0 0 20px 0;">
            <div class="col-md-3 col-sm-3 col-xs-12 site-title">
                <a href="/">
                    @Html.LocalImage("App", "logo.png", "WebMarket.com", "img-responsive", "WebMarket.com")
                </a>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12 search-panel collapse" id="pnlSearch">
                <input type="text" class="search-box" placeholder="@Resource.SearchItem" maxlength="100" />
                <button class="btn-search"><i class="fa fa-search"></i></button>
                <div class="search-results"></div>
            </div>

            <div class="mt20 col-md-3 col-sm-3 col-member">
                @Html.Partial("_MyAccount", Model)
                <a href="@Url.Action("MyFavorites", "Product")" class="hidden-xs btn btn-black-border btn-favorites"><i class="fa fa-heart"></i></a>
                <a href="#" class="btn btn-black-border btn-basket-summary">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="hidden-xs hidden-sm"> @Resource.Basket_Title </span>
                    <span class="item-count">0</span>
                </a>
                <a href="javascript:void(0);" class="btn btn-black-border menu-toggle btn-top-menu"><i class="fa fa-bars"></i></a>
                <a href="javascript:void(0);" class="visible-xs btn btn-black-border btn-search-xs collapsed" data-toggle="collapse" data-target="#pnlSearch"><i></i></a>

                <div class="basket-summary-container" data-loaded="0">
                    <div class="loading">
                        <p class="lead">Yükleniyor..</p>
                        <img src="/resource/img/Icons/processing.gif" class="mt10 process" alt="">
                    </div>
                    <div class="summary hide"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="top-menu">
        <div class="container">
            <nav class="navigation closed clearfix">
                <div class="menu-toggle-close"><i class="fa fa-bars menu-toggle"></i> <span>Menü</span></div>
                <ul class="nav sf-menu">

                    @if (Model.IsLoggedIn)
                    {
                        <li class="megamenu visible-xs user"><a href="/bilgilerim">Merhaba, @Model.UserInfo</a></li>
                    }
                    else
                    {
                        <li class="megamenu visible-xs user"><a href="/uye-girisi">Üye Girişi</a></li>
                    }

                    <li class="megamenu visible-xs has-icon"><a href="/marketler"><i class="fa fa-tv"></i> &nbsp;Marketler</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/urunler"><i class="fa fa-cubes"></i> &nbsp;Ürünler</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/kampanyalar"><i class="fa fa-tags"></i> &nbsp;Kampanyalar</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/sepetim"><i class="fa fa-shopping-cart"></i> &nbsp;Sepetim</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/siparislerim"><i class="fa fa-truck"></i> &nbsp;Siparişlerim</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/favorilerim"><i class="fa fa-heart"></i> &nbsp;Favorilerim</a></li>


                    @foreach (var item in Model.TopMenuItems)
                    {
                        <li data-id="@item.ID" class="megamenu category">
                            <a href='@Url.CategoryItemList(item.ID, item.Name)'>
                                @*<i class="category-icon" style="background: url('/resource/img/Category/icon_@(item.ID).png') no-repeat;"></i>*@
                                @item.Name
                            </a>
                            <ul>
                                <li class="row">
                                    <div class="col-md-12 menu-detail" data-id="@item.ID">
                                        <h3 class="mb10 mb20 hidden-xs text-left">@item.Name</h3>
                                        @foreach (var subItem in item.SubCategories)
                                        {
                                            <a class="sub-cat" href="@Url.CategoryItemList(subItem.ID, subItem.Name)" title="@subItem.Name">
                                                <img class="subcat-img hidden-xs" src="/resource/img/Category/@(subItem.ID).png" alt="@subItem.Name" />
                                                @subItem.Name.Short(16)
                                            </a>
                                        }
                                        <img class="cat-img hidden-xs" src="/resource/img/Category/@(item.ID).png" alt="@item.Name" />
                                    </div>
                                </li>
                            </ul>
                        </li>
                    }


                    <li class="megamenu visible-xs has-icon"><a href="/semt-sec"><i class="fa fa-random"></i> &nbsp;Semt Değiştir</a></li>
                    <li class="megamenu visible-xs has-icon"><a href="/iletisim"><i class="fa fa-phone"></i> &nbsp;İletişim</a></li>
                    @if (Model.IsLoggedIn)
                    {
                        <li class="megamenu visible-xs logout"><a href="/oturumu-sonlandir">Oturumu Sonlandır</a></li>
                    }

                    <li data-id="0" class="megamenu hidden-xs">
                        <a href="/kampanyalar">Kampanyalar</a>
                    </li>
                    <li class="megamenu visible-xs"><a href="#"></a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

@Html.Partial("_SiteModals", Model)
@Html.Hidden("FavoriteProducts", Model.FavoriteProducts != null ? string.Join(",", Model.FavoriteProducts).S() : "")
@Html.Hidden("HasNotification", Model.HasNotification ? 1 : 0)
@*@Html.Hidden("SiteLanguage", Aware.Common.Language == "en-US" ? 1 : 0)*@