WebMarket/WebMarket.Admin/Controllers/CommonController.cs
using System.Collections.Generic;
using System.Linq;
using System.Collections.Specialized;
using System.Web.Mvc;
using Aware.Authenticate;
using Aware.Authority.Model;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Model;
using Aware.ECommerce.Model.Custom;
using Aware.Mail;
using Aware.Payment.Model;
using Aware.Util;
using Aware.Util.Model;
using Aware.ECommerce.Enums;
using Aware.Util.Enums;
using Aware.Util.Lookup;

namespace WebMarket.Admin.Controllers
{
    [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser, new[] { "Common/AuthorityUsage" })]
    public class CommonController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IMailService _mailService;
        private readonly IPaymentService _paymentService;
        private readonly ICommonService _commonService;
        private readonly ILookupManager _lookupManager;
        public CommonController(IMailService mailService, IUserService userService, IPaymentService paymentService, ICommonService commonService, ILookupManager lookupManager)
        {
            _mailService = mailService;
            _userService = userService;
            _paymentService = paymentService;
            _commonService = commonService;
            _lookupManager = lookupManager;
        }

        #region Site Settings

        public ActionResult SiteSettings()
        {
            ViewBag.YesNoOptions = _lookupManager.GetLookups(LookupType.YesNoOptions);
            var model = _commonService.GetSiteSettings();
            return View(model);
        }

        [HttpPost]
        public ActionResult SiteSettings(SiteModel model)
        {
            var result = _commonService.SaveSiteSettings(model);
            ViewBag.SaveResult = result;
            ViewBag.YesNoOptions = _lookupManager.GetLookups(LookupType.YesNoOptions);

            return View(result.ValueAs<SiteModel>());
        }

        public ActionResult OrderSettings()
        {
            var model = _commonService.GetSimpleItems(ItemType.OrderSettings);
            ViewBag.PosList = _paymentService.GetPosDefinitions(true).Select(i => new Item(i.ID, i.Name)).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult OrderSettings(List<SimpleItem> model)
        {
            foreach (var item in model)
            {
                _commonService.SaveSimpleItem(item);
            }

            model = _commonService.GetSimpleItems(ItemType.OrderSettings);
            ViewBag.PosList = _paymentService.GetPosDefinitions(true).Select(i => new Item(i.ID, i.Name)).ToList();
            ViewBag.SaveResult = Result.Success();
            return View(model);
        }

        public ActionResult SimpleItems(ItemType itemType = ItemType.None)
        {
            ArrangeSimpleItemsTitle(itemType);
            var model = new SimpleItemListModel()
            {
                StatusList = _lookupManager.GetLookups(LookupType.Status),
                List = _commonService.GetSimpleItems(itemType)
            };
            return View(model);
        }

        [HttpPost]
        public JsonResult LoadSimpleItem(int itemID)
        {
            var item = new SimpleItem();
            if (itemID > 0)
            {
                item = _commonService.GetSimpleItem(itemID);
            }
            return Json(new { success = (item != null ? 1 : 0), item }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult SaveSimpleItem(SimpleItem model)
        {
            var result = _commonService.SaveSimpleItem(model);
            return Json(new { success = result.IsSuccess, message = result.Message, itemID = result.Value }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult RemoveSimpleItem(int itemID)
        {
            var result = _commonService.DeleteSimpleItem(itemID);
            return ResultValue(result);
        }

        #endregion

        #region Cache Management

        public ActionResult CacheManagement()
        {
            var url = string.Format("{0}/GetCacheKeys", ServiceUrl);
            var values = new NameValueCollection();
            values["ticket"] = GetTicket();

            var result = WebRequester.DoRequest<Result>(url, true, values);
            if (result != null && result.OK)
            {
                var model = result.Value as IEnumerable<object>;
                return View(model);
            }
            return View();
        }

        [HttpPost]
        public JsonResult ClearCache(string cacheKey)
        {
            var isSuccess = 0;
            var url = string.Format("{0}/ClearCache", ServiceUrl);
            var values = new NameValueCollection();
            values["ticket"] = GetTicket();
            values["cacheKey"] = cacheKey;

            var result = WebRequester.DoRequest<Result>(url, true, values);
            if (result != null && result.OK)
            {
                isSuccess = 1;
            }
            return Json(new { isSuccess }, JsonRequestBehavior.DenyGet);
        }

        #endregion

        #region Mail Templates

        public ActionResult MailTemplates()
        {
            return View("MailTemplates", GetMailTemplates());
        }

        public ActionResult MailTemplate(int id)
        {
            var mailTemplates =GetMailTemplates();
            ViewBag.MasterTemplates = mailTemplates.Where(i => i.ParentID == 0).Select(i => new Item(i.ID, i.Name));

            var model = id > 0 ? mailTemplates.FirstOrDefault(i => i.ID == id) : new MailTemplate();
            return View("MailTemplate", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult MailTemplate(MailTemplate model)
        {
            var result = Result.Error();
            if (ModelState.IsValid)
            {
                result = _mailService.Save(model);
                if (result.OK) { model = result.ValueAs<MailTemplate>(); }
            }

            var mailTemplates = GetMailTemplates();
            ViewBag.MasterTemplates = mailTemplates.Where(i => i.ParentID == 0).Select(i => new Item(i.ID, i.Name));
            ViewBag.SaveResult = result;
            return View("MailTemplate", model);
        }

        private List<MailTemplate> GetMailTemplates()
        {
            var result = _mailService.GetAll(1,250).ToList();
            if (result.Any())
            {
                return result.Select(i =>
                {
                    i.Parent = result.FirstOrDefault(s => s.ID == i.ParentID);
                    return i;
                }).ToList();
            }
            return result;
        }

        #endregion

        #region Authority

        public ActionResult AuthorityDefinition()
        {
            var model = _commonService.GetAuthorityDefinitions(true);
            return View(model);
        }

        [Aware.Util.Filter.Authorize]
        public ActionResult AuthorityUsage(int relationID, int relationType)
        {
            ViewBag.RelationID = relationID;
            ViewBag.RelationType = relationType;
            ViewBag.AllowSave = CurrentUser.IsAdmin;
            if (relationType == (int)RelationTypes.User && relationID == CurrentUserID) { ViewBag.AllowSave = false; }

            var model = _commonService.GetAuthorityUsages(relationID, relationType, IsSuper(false));
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult GetAuthorityDetail(int id)
        {
            var authority = _commonService.GetAuthorityDefinition(id);
            return Json(new { authority }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        public JsonResult SaveAuthority(int id, string title, AuthorityType type, AuthorityMode mode)
        {
            var result = _commonService.SaveAuthority(new AuthorityDefinition
            {
                ID = id,
                Title = title,
                Type = type,
                Mode = mode
            });
            return ResultValue(result);
        }

        [HttpPost]
        public JsonResult SaveAuthorityUsage(int relationID, int relationType, List<AuthorityUsage> authorities)
        {
            var enableQuota = IsSuper(false);
            var result = _commonService.SaveAuthorityUsage(relationID, relationType, authorities, enableQuota);
            return ResultValue(result);
        }

        [HttpPost]
        public JsonResult DeleteAuthority(int authorityID)
        {
            var result = _commonService.DeleteAuthority(authorityID);
            return ResultValue(result);
        }

        #endregion

        #region Online Pos Management

        public ActionResult OnlinePos()
        {
            var model = _paymentService.GetPosDefinitions();
            return View(model);
        }

        public ActionResult OnlinePosDetail(int id)
        {
            var model = _paymentService.GetPosDefinitionDetail(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult OnlinePosDetail(PosDefinition model)
        {
            var result = Result.Error();
            if (ModelState.IsValid)
            {
                var isNew = model.ID == 0;
                result = _paymentService.SavePosDefinition(model);
                if (result.OK)
                {
                    model = result.ValueAs<PosDefinition>();
                    if (isNew)
                    {
                        return RedirectToRoute(Helper.RouteNames.OnlinePosDetailRoute, new { id = model.ID });
                    }
                }
            }

            ViewBag.SaveResult = result;
            var detailModel = _paymentService.GetPosDefinitionDetail(model.ID);
            return View(detailModel);
        }

        #endregion

        #region Helpers

        private string GetTicket()
        {

WebMarket/WebMarket.Admin/Controllers/OrderController.cs
using System.Linq;
using System.Web.Mvc;
using Aware.ECommerce.Interface;
using Aware.ECommerce.Model;
using WebMarket.Admin.Models.ModelBinder;
using System.Collections.Generic;
using Aware.ECommerce.Search;
using Aware.Payment.Model;
using Aware.Regional;
using Aware.Regional.Model;
using Aware.Util.Model;
using Aware.Util.Enums;
using Aware.ECommerce.Enums;
using WebMarket.Admin.Helper;

namespace WebMarket.Admin.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService _orderService;
        private readonly IPaymentService _paymentService;
        private readonly IAddressService _addressService;
        public OrderController(IOrderService orderService, IAddressService addressService, IPaymentService paymentService)
        {
            _orderService = orderService;
            _addressService = addressService;
            _paymentService = paymentService;
        }

        public ActionResult Index([ModelBinder(typeof(OrderSearchBinder))] OrderSearchParams searchParams, int customerID = 0)
        {
            customerID = CurrentUser.IsSuper ? customerID : CurrentUser.CustomerID;
            if (!IsValidOperation(customerID) || (CurrentUser.IsSuper && customerID <= 0))
            {
                return RedirectToRoute(RouteNames.NotFoundRoute);
            }

            searchParams.WithCount();
            var model = _orderService.SearchOrders(searchParams, customerID);
            return View(model);
        }

        public ActionResult Detail(int id)
        {
            var model = _orderService.GetOrderViewModel(id, -1, 0, true);
            return View(model);
        }

        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public ActionResult ShippingMethods()
        {
            ViewBag.RegionList = GetRegions();
            var model = _orderService.GetAllShippingMethods();
            return View(model);
        }

        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public ActionResult ShippingMethod(int id)
        {
            ViewBag.RegionList = GetRegions().Select(i => new Item(i.ID, i.Name)).ToList();
            var model = id > 0 ? _orderService.GetShippingMethod(id) : new ShippingMethod();
            return View(model);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public ActionResult ShippingMethod(ShippingMethod model)
        {
            var result = Result.Error();
            if (ModelState.IsValid)
            {
                var isNew = model.ID == 0;
                result = _orderService.SaveShippingMethod(model);
                if (result.OK)
                {
                    model = result.ValueAs<ShippingMethod>();
                    if (isNew)
                    {
                        return RedirectToRoute(Helper.RouteNames.ProductDetailRoute, new { id = model.ID });
                    }
                }
            }

            ViewBag.SaveResult = result;
            ViewBag.RegionList = GetRegions().Select(i => new Item(i.ID, i.Name)).ToList();
            return View(model);
        }

        [HttpPost]
        public JsonResult ChangeStatus(int id, OrderStatuses status)
        {
            var result = _orderService.ChangeOrderStatus(id, status);
            return Json(new { success = result.IsSuccess, message = result.Message }, JsonRequestBehavior.AllowGet);
        }

        private List<Region> GetRegions()
        {
            var list = new List<Region>() { new Region() { ID = -1, Name = "Tümü" } };
            list.AddRange(_addressService.SearchRegions(string.Empty,null));
            return list;
        }

        #region Bank Management

        public ActionResult BankInfo()
        {
            if (!IsSuper(false))
            {
                var model = _paymentService.GetBankList();
                return View("BankList", model);
            }
            return View();
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult GetBankList()
        {
            var model = _paymentService.GetBankList();
            return Json(new { model }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult SaveBankInfo(BankInfo model)
        {
            var result = _paymentService.SaveBankInfo(model);
            return Json(new { success = result.IsSuccess, message = result.Message, itemID = result.Value }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult DeleteBankInfo(int bankID)
        {
            var result = _paymentService.DeleteBankInfo(bankID);
            return ResultValue(result);
        }

        #endregion

        #region InstallmentInfo Management

        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public ActionResult InstallmentInfo()
        {
            return View();
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult GetInstallmentList()
        {
            var posList = new List<Item>();
            var posDefinitions = _paymentService.GetPosDefinitions();

            if (posDefinitions != null && posDefinitions.Any())
            {
                var model = _paymentService.GetInstallmentList();
                posList = posDefinitions.OrderBy(i => !i.IsTest).Select(i => new Item(i.ID, i.Name)).ToList();
                return Json(new { model, posList }, JsonRequestBehavior.DenyGet);
            }
            return Json(new { posList }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult SaveInstallmentInfo(InstallmentInfo model)
        {
            var result = _paymentService.SaveInstallmentInfo(model);
            return Json(new { success = result.IsSuccess, message = result.Message, itemID = result.Value }, JsonRequestBehavior.DenyGet);
        }

        [HttpPost]
        [Aware.Util.Filter.Authorize(AuthorizeLevel.SuperUser)]
        public JsonResult DeleteInstallmentInfo(int installmentID)
        {
            var result = _paymentService.DeleteInstallmentInfo(installmentID);
            return ResultValue(result);
        }

        #endregion
    }
}

WebMarket/WebMarket.Admin/Views/Common/OnlinePos.cshtml
@using WebMarket.Admin.Helper
@model IEnumerable<Aware.Payment.Model.PosDefinition>
@{
    ViewBag.Title = "Sanal Poslar";
    TempData["ActivePage"] = 27;
    var count = Model != null ? Model.Count() : 0;
}

<section class="container-fluid">
    <div class="row">
        <div class="@(count > 0 ? "col-md-12" : "col-md-9")">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-th"></i></div>
                <div class="card-content">
                    <h2 class="card-title">
                        @ViewBag.Title
                        <a href="@Url.Action("OnlinePosDetail", "Common", new {id = 0})" class="btn btn-info btn-round btn-fab btn-fab-mini"><i class="fa fa-plus"></i></a>
                    </h2>
                    
                    <div class="nav-tabs-custom">
                        <ul class="nav nav-tabs">
                            <li><a href="@Url.Action("OrderSettings", "Common")">Sipariş Ayarları</a></li>
                            <li><a href="@Url.Action("ShippingMethods", "Order")"><i class="fa fa-truck"></i> Kargo Yönetimi</a></li>
                            <li class="active"><a href="#tab_general" data-toggle="tab" aria-expanded="false"><i class="fa fa-credit-card"></i> Sanal Poslar</a></li>
                            <li><a href="@Url.Action("BankInfo", "Order")"><i class="fa fa-bank"></i> Bankalar</a></li>
                            <li><a href="@Url.Action("InstallmentInfo", "Order")"><i class="fa fa-pie-chart"></i> Taksit & Komisyon</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab_general">
                                @if (count > 0)
                                {
                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>#ID</th>
                                                    <th colspan="2">İsim</th>
                                                    <th>Pos Tipi</th>
                                                    <th>Terminal No</th>
                                                    <th>İş Yeri No</th>
                                                    <th>Kullanıcı</th>
                                                    <th>Test?</th>
                                                    <th>İşlemler</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td width="2%">@item.ID</td>
                                                        <td width="8%">@Html.ImageFor("Bank", (!string.IsNullOrEmpty(item.ImageUrl) ? item.ImageUrl : "0.jpg"), "", "image bank-image")</td>
                                                        <td width="15%">@item.Name</td>
                                                        <td width="20%">@item.PosType.ToString() - @item.PaymentMethod.ToString()</td>
                                                        <td width="8%">@item.TerminalID</td>
                                                        <td width="8%">@item.MerchantID</td>
                                                        <td width="6%">@item.UserID</td>
                                                        <td width="4%">@(item.IsTest ? "Evet" : "Hayır")</td>
                                                        <td>
                                                            <a href="@Url.Action("OnlinePosDetail", "Common", new {id = item.ID})" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Görüntüle</a>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                }
                                else
                                {
                                    <div class="no-result-found">
                                        <i class="fa fa-warning"></i>
                                        <h4>Sistemde tanımlı sanal pos bulunamadı!</h4>
                                        <p class="description"><b>Yeni Ekle</b> butonunu kullanarak yeni öğe ekleyebilirsiniz.</p>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

WebMarket/WebMarket.Admin/Views/Common/OrderSettings.cshtml
@using Aware.ECommerce.Enums
@using Aware.Util
@using Aware.ECommerce.Model
@using Aware.Util.Enums
@using Aware.Util.Model
@using Aware.Util.View
@using WebMarket.Admin.Helper
@model List<SimpleItem>
@{
    TempData["ActivePage"] = 27;
    ViewBag.Title = "Sipariş Ayarları";

    var settings = Util.ArrangeOrderSettings(Model);
    var singleSelect = settings.Where(i => i.SubType >= (int)OrderSettingsType.AllowShipping).ToList();
    var paymentTypes = settings.Where(i => i.SubType < (int)OrderSettingsType.AllowShipping).ToList();
    var posList = ViewBag.PosList != null ? (List<Item>)ViewBag.PosList : new List<Item>();
}

<section class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header card-header-icon"><i class="fa fa-th"></i></div>
                <div class="card-content">
                    <h2 class="card-title">@ViewBag.Title</h2>
                    
                    @using (Html.BeginForm("OrderSettings", "Common", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
                    {
                        <div class="nav-tabs-custom">
                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#tab_general" data-toggle="tab" aria-expanded="false">Sipariş Ayarları</a></li>
                                <li><a href="@Url.Action("ShippingMethods", "Order")"><i class="fa fa-truck"></i> Kargo Yönetimi</a></li>
                                <li><a href="@Url.Action("OnlinePos", "Common")"><i class="fa fa-credit-card"></i> Sanal Poslar</a></li>
                                <li><a href="@Url.Action("BankInfo", "Order")"><i class="fa fa-bank"></i> Bankalar</a></li>
                                <li><a href="@Url.Action("InstallmentInfo", "Order")"><i class="fa fa-pie-chart"></i> Taksit & Komisyon</a></li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tab_general">
                                    <p>
                                        Bu alanda siparişleriniz için ödeme yöntemlerini belirleyebilir,
                                        aynı zamanda siparişleriniz için kargo kullanımını etkinleştirebilirsiniz.
                                    </p>

                                    <table class="mt20 table">
                                        <thead>
                                            <tr>
                                                <th>İşlem</th>
                                                <th>Onay?</th>
                                                <th>Ek Fiyat</th>
                                                <th>Açıklama</th>
                                            </tr>
                                        </thead>

                                        @for (var i = singleSelect.Count; i < settings.Count; i++)
                                        {
                                            var paymentType = paymentTypes[i - singleSelect.Count];
                                            <tr>
                                                <td width="15%">@paymentType.Title</td>
                                                <td width="4%">
                                                    @Html.Hidden("Model[" + i + "].ID", paymentType.ID)
                                                    @Html.Hidden("Model[" + i + "].Type", (int)paymentType.Type)
                                                    @Html.Hidden("Model[" + i + "].SubType", paymentType.SubType)
                                                    @Html.Hidden("Model[" + i + "].Title", paymentType.Title)

                                                    <div class="cbx @(paymentType.Status == Statuses.Active ? "active" : "")" data-value-type="byte">
                                                        @Html.Hidden("Model[" + i + "].Status", (int)paymentType.Status)
                                                        <i class="fa fa-check"></i>
                                                    </div>
                                                </td>
                                                <td width="10%">
                                                    @Html.TextBox("Model[" + i + "].Cost", paymentType.Cost, new { @class = "dec-number text-right form-control", maxlength = 6 })
                                                </td>
                                                <td width="25%">
                                                    @Html.TextBox("Model[" + i + "].Value", paymentType.Value, new { @class = "form-control", maxlength = 200 })
                                                </td>
                                            </tr>
                                        }

                                        @for (var i = 0; i < singleSelect.Count; i++)
                                        {
                                            var setting = singleSelect[i];
                                            var isDefaultPos = setting.SubType == (int)OrderSettingsType.DefaultPos;
                                            <tr>
                                                <td>
                                                    @setting.Title
                                                    @if (setting.SubType == (int)OrderSettingsType.UseOOSPayment)
                                                    {
                                                        <i class="ml10 fa fa-info-circle" data-toggle="tooltip" title="Ödemeler için kullanıcı seçilen sanal posun ortak ödeme sayfasına yönlendirilir."></i>
                                                    }
                                                </td>
                                                <td colspan="@(isDefaultPos ? 1 : 3)">
                                                    @Html.Hidden("Model[" + i + "].ID", setting.ID)
                                                    @Html.Hidden("Model[" + i + "].Title", setting.Title)
                                                    @Html.Hidden("Model[" + i + "].SubType", (int)setting.SubType)
                                                    @Html.Hidden("Model[" + i + "].Type", (int)setting.Type)

                                                    <div class="cbx @(setting.Status == Statuses.Active ? "active" : "")" data-value-type="byte">
                                                        @Html.Hidden("Model[" + i + "].Status", (int)setting.Status)
                                                        <i class="fa fa-check"></i>
                                                    </div>
                                                </td>

                                                @if (isDefaultPos)
                                                {
                                                    var fieldHelper = new FieldHelper(FieldDirection.JustField);
                                                    fieldHelper.Select(string.Empty, "Model[" + i + "].Value", posList, setting.Value.Int(), "form-control");
                                                    <td>
                                                        @Html.Partial("_FieldHelper", fieldHelper)
                                                    </td>
                                                    <td></td>
                                                }
                                            </tr>
                                        }
                                    </table>
                                    
                                    <hr/>
                                    <div class="box-footer">
                                        @Html.ButtonFor("Değişiklikleri Yayınla", "mr10 btn-info btn-clear-cache", "history", "data-cache-key='ORDER_SETTINGS'")
                                        @Html.ButtonFor("Değişiklikleri Kaydet", "fr btn-success btn-save-settings")
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>